---
- name: Verify
  hosts: all
  become: yes
  gather_facts: yes

  tasks:
    - name: Check if port 8080 is available
      ansible.builtin.wait_for:
        port: 8080

    - name: Get a page from Tomcat
      ansible.builtin.uri:
        url: "http://localhost:8080/"

    - name: See if sensitive information is not exposed
      ansible.builtin.uri:
        url: "http://localhost:8080/"
        return_content: yes
      register: this
      failed_when:
        - "'successfully installed Tomcat' in this.content"
